name: Makefile for git actions

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: make install-dependencies

      - name: Install tools
        run: make install-tools

      - name: Install
        run: make install

      - name: Run lint
        run: make lint

      - name: Run test
        run: make test-verbose-with-coverage

      - name: Run gover
        run: gover
